In [140]:
#importing the python libraries for ML
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [141]:
# Reading the training file
SVM= pd.read_csv('DengAI_Predicting_Disease_Spread_-_Training_Data_Features.csv')

In [142]:
#Importing Total number of cases from the Total cases file
SVM_Cases= pd.read_csv('DengAI_Predicting_Disease_Spread_-_Training_Data_Labels.csv')
SVM_Cases.head(10)

city  year  weekofyear  total_cases
0   sj  1990          18            4
1   sj  1990          19            5
2   sj  1990          20            4
3   sj  1990          21            3
4   sj  1990          22            6
5   sj  1990          23            2
6   sj  1990          24            4
7   sj  1990          25            5
8   sj  1990          26           10
9   sj  1990          27            6

In [143]:
len(SVM)

1456

In [144]:
#RawData1.count()

In [145]:
# Importing the Total Number of cases 
SVM['Total_Cases'] = SVM_Cases['total_cases']
SVM.count()

city                                     1456
year                                     1456
weekofyear                               1456
week_start_date                          1456
ndvi_ne                                  1262
ndvi_nw                                  1404
ndvi_se                                  1434
ndvi_sw                                  1434
precipitation_amt_mm                     1443
reanalysis_air_temp_k                    1446
reanalysis_avg_temp_k                    1446
reanalysis_dew_point_temp_k              1446
reanalysis_max_air_temp_k                1446
reanalysis_min_air_temp_k                1446
reanalysis_precip_amt_kg_per_m2          1446
reanalysis_relative_humidity_percent     1446
reanalysis_sat_precip_amt_mm             1443
reanalysis_specific_humidity_g_per_kg    1446
reanalysis_tdtr_k                        1446
station_avg_temp_c                       1413
station_diur_temp_rng_c                  1413
station_max_temp_c                

In [146]:
SVM = SVM.fillna(value=SVM.mean())
SVM.head(5)

city  year  weekofyear week_start_date   ndvi_ne   ndvi_nw   ndvi_se  \
0   sj  1990          18      1990-04-30  0.122600  0.103725  0.198483   
1   sj  1990          19      1990-05-07  0.169900  0.142175  0.162357   
2   sj  1990          20      1990-05-14  0.032250  0.172967  0.157200   
3   sj  1990          21      1990-05-21  0.128633  0.245067  0.227557   
4   sj  1990          22      1990-05-28  0.196200  0.262200  0.251200   

    ndvi_sw  precipitation_amt_mm  reanalysis_air_temp_k  ...  \
0  0.177617                 12.42             297.572857  ...   
1  0.155486                 22.82             298.211429  ...   
2  0.170843                 34.54             298.781429  ...   
3  0.235886                 15.36             298.987143  ...   
4  0.247340                  7.52             299.518571  ...   

   reanalysis_relative_humidity_percent  reanalysis_sat_precip_amt_mm  \
0                             73.365714                         12.42   
1                             77.368571                         22.82   
2                             82.052857                         34.54   
3                             80.337143                         15.36   
4                             80.460000                          7.52   

   reanalysis_specific_humidity_g_per_kg  reanalysis_tdtr_k  \
0                              14.012857           2.628571   
1                              15.372857           2.371429   
2                              16.848571           2.300000   
3                              16.672857           2.428571   
4                              17.210000           3.014286   

   station_avg_temp_c  station_diur_temp_rng_c  station_max_temp_c  \
0           25.442857                 6.900000                29.4   
1           26.714286                 6.371429                31.7   
2           26.714286                 6.485714                32.2   
3           27.471429                 6.771429                33.3   
4           28.942857                 9.371429                35.0   

   station_min_temp_c  station_precip_mm  Total_Cases  
0                20.0               16.0            4  
1                22.2                8.6            5  
2                22.8               41.4            4  
3                23.3                4.0            3  
4                23.9                5.8            6  

[5 rows x 25 columns]

In [147]:
#WE are removing the Yean and City Column as they do mot hae any correlation with the rest of the data
#x = np.delete(x1,[0,3],1)
#x = np.delete(x,0,1)
x = SVM[[ 'weekofyear',  'reanalysis_air_temp_k','reanalysis_dew_point_temp_k',
          'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
          'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
          'reanalysis_specific_humidity_g_per_kg', 'station_max_temp_c','station_min_temp_c', ]]

In [148]:
# We are assigning the Y values to the Total Cases as we need to train the Data for running the model on TEST dataset
y = SVM['Total_Cases'].values

In [149]:
y

array([4, 5, 4, ..., 1, 1, 4], dtype=int64)

In [150]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y, test_size = 0.2, random_state = 100)
y_test

array([  1, 220,  11,  16,   3,  18,  19,   6,  27,   5,   5,   9,   5,
         9,   2,   4,  72,   1,   3,  22,  10,   9,   3,  31,   2,   6,
        30,  33,  11,   7,   4,   3,   6,   1,  18,   4,   4,  53,   3,
        28,   5,  46,   2,  51,  16,  50,   6,  14,  23,   1,   0,   8,
        22,  18,   4,  19,   0,   1,  12,   6,  17,  17,  22,  11,  10,
        44,  10,   9,  60,  67,   2,  30,  11,  34,   0,  17,  38,   6,
        16,  16,   1,   9,  34,  20,  32,   3,  56,  19,  18,  13,   0,
       461,  33,  12,   7,  47,  24,   4, 149,   5,  22,  10,  14,   2,
        50,   2,  13,   0,  36,   1,  44,   7,  11,   7,   4,   4,   8,
        23,  21,  12,  25,  12,   9,  23,  28,   2,   6,  43,  91,   9,
         5,   3,   6,  17,   6,   8, 115,  12,   4,   0,  19,  14,   3,
        19,   9,   7,  17,  35,  24,   2,  25,  59, 359,   2,  40,   1,
         4,  46,   9,   7,  26,  11,   3,   2,  11,  18,   9,   1,  35,
         0,  29,  16,   6,  16,  28,  13,  29,   4,  20,   6,   

In [151]:
# Linear Regression
from sklearn.svm import SVC
SVM = SVC(C=10)
SVM.fit(x_train, y_train)

C:\Users\niahmad\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [152]:
SVM.score(x_test,y_test)

0.0684931506849315

In [153]:
SVM.score(x_train,y_train)

0.993127147766323

In [154]:
x_train.columns

Index(['weekofyear', 'reanalysis_air_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'station_max_temp_c',
       'station_min_temp_c'],
      dtype='object')

In [155]:
#predicting Linear Regression
y_pred=SVM.predict(x_test)
y_pred

array([  0,   0,   0,   7,   0,  75,  10,   0,  12,   1,   0,   0,  27,
        11,   0,   0,  14,   1,   6,   0,   7,   0,   0,   5,   0,  14,
         0,  17,  28,   0,   0,   0,  21,   0,   9,   5,   0,   0,  18,
        37,   0,   7,   0,  18,   0,  34,   7,  18,   0,   1,   0,  10,
         0,  28,  47,   0,   1,   0,   0,   0,  62,   4,   6,   0,  29,
        47,   1,   0,   0,   0,   0,   3,   5,  20,   0,  14,  18,   1,
         0,   5,   0,   6,   0,   2,  35,   0,  23,  12,   0,  13,   2,
         0,   2,   0,   0,   0,   9,   1,  36,   5,   0,   0,   9,   0,
        17,  50,   0,   2,  26,   0,  11,   0,   6,  16,   0,   0,  13,
        12,   0,  28,   0,   0,  25,  55,   3,   0,   0,   0,   7,   0,
        20,   7,   0,  10,   0,  29,  16,   0,   1,   0,   0,   7,   7,
         0,   0,   1,   0,   0,  10,   0,  21,  37,   0,   0,   0,   2,
         8,   0,   0,   0,  14,   0,   4,   4,   0,   0,   5,   0,   0,
         0,   0,   0,   0,   0,   2,   0,  37,   0,   0,   5,   

In [156]:
#Linear Regression
(y_test)

array([  1, 220,  11,  16,   3,  18,  19,   6,  27,   5,   5,   9,   5,
         9,   2,   4,  72,   1,   3,  22,  10,   9,   3,  31,   2,   6,
        30,  33,  11,   7,   4,   3,   6,   1,  18,   4,   4,  53,   3,
        28,   5,  46,   2,  51,  16,  50,   6,  14,  23,   1,   0,   8,
        22,  18,   4,  19,   0,   1,  12,   6,  17,  17,  22,  11,  10,
        44,  10,   9,  60,  67,   2,  30,  11,  34,   0,  17,  38,   6,
        16,  16,   1,   9,  34,  20,  32,   3,  56,  19,  18,  13,   0,
       461,  33,  12,   7,  47,  24,   4, 149,   5,  22,  10,  14,   2,
        50,   2,  13,   0,  36,   1,  44,   7,  11,   7,   4,   4,   8,
        23,  21,  12,  25,  12,   9,  23,  28,   2,   6,  43,  91,   9,
         5,   3,   6,  17,   6,   8, 115,  12,   4,   0,  19,  14,   3,
        19,   9,   7,  17,  35,  24,   2,  25,  59, 359,   2,  40,   1,
         4,  46,   9,   7,  26,  11,   3,   2,  11,  18,   9,   1,  35,
         0,  29,  16,   6,  16,  28,  13,  29,   4,  20,   6,   

In [157]:
from sklearn import metrics

In [158]:
metrics.mean_absolute_error(y_test, y_pred)

22.21917808219178

In [159]:
metrics.mean_squared_error(y_test, y_pred)

2421.9109589041095

In [160]:
np.sqrt(metrics.mean_squared_error(y_test, y_pred))

49.212914554048815

In [161]:
from sklearn.model_selection import train_test_split

In [162]:
from sklearn.ensemble import RandomForestRegressor 

In [163]:
regressor = RandomForestRegressor(n_estimators=300)

In [164]:
from sklearn.metrics import r2_score
R2 = r2_score(y_test, y_pred)
R2

-0.19806059076944726

In [165]:
from sklearn.metrics import r2_score
R2 = r2_score(y_test, y_pred)
R2

-0.19806059076944726